# Nome da aplicação
spring.application.name=dss-at

# Configuração do banco PostgreSQL (Neon Console)
spring.datasource.url=jdbc:postgresql://ep-soft-wind-acj7gyfs-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_iElZ9cbfC5dj
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Actuator - expor apenas o endpoint de health
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
