spring.application.name=tp3-dss
spring.datasource.url=jdbc:h2:mem:tp3dssdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=false
# docker run -d -p 27017:27017 --name mongodb mongo:latest no cmd
spring.mongodb.uri=mongodb://localhost:27017/academia
spring.data.redis.host=localhost
spring.data.redis.port=6379
management.health.redis.enabled=true
# docker run -d -p 6379:6379 --name redis redis:latest